// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCVihiHxjIiXkTAF_e6vOi9TvzD7LdQ0',
    appId: '1:400554224855:web:cedb7d59c45dc62e7f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    authDomain: 'mohamed-portfolio-a37de.firebaseapp.com',
    storageBucket: 'mohamed-portfolio-a37de.appspot.com',
    measurementId: 'G-DSGQH2XGBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPH5nLJeXI1VpkUy-3gTPwnKxuuXO5Og',
    appId: '1:400554224855:android:5d1d4f56c869ef117f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    storageBucket: 'mohamed-portfolio-a37de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyErbfHP-QOB7PqJGQQdh10QkRxtQkl24',
    appId: '1:400554224855:ios:3f33e56b6382032e7f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    storageBucket: 'mohamed-portfolio-a37de.appspot.com',
    iosClientId:
        '400554224855-1vnfiucmfiimulsr9vkcgja7gl72hiaf.apps.googleusercontent.com',
    iosBundleId: 'com.hmz.folio',
  );
}
