class ProjectUtils {
  static const List<String> banners = [
    "assets/projects/hayat_almuslim.webp",
    "assets/projects/bank_eldam.webp",
    "assets/projects/tejara.webp",
    "assets/projects/wardi.webp",
    "assets/projects/afaky.webp",
    "assets/projects/gala.webp",
    "assets/projects/gala_driver.webp",
    "assets/projects/qr_pro.webp",
    "assets/projects/allemny.webp",
    "assets/projects/jayek.webp",
    "assets/projects/electronic_contracts.webp",
    "assets/projects/h2h.webp",
    "assets/projects/stories.webp",
    "assets/projects/almotaheda.png",
    "assets/projects/helpers.webp",
  ];

  static const List<String> icons = [
    "assets/projects/hayat_almuslim.webp",
    "assets/projects/bank_eldam.webp",
    "assets/projects/tejara.webp",
    "assets/projects/wardi.webp",
    "assets/projects/afaky.webp",
    "assets/projects/gala.webp",
    "assets/projects/gala_driver.webp",
    "assets/projects/qr_pro.webp",
    "assets/projects/allemny.webp",
    "assets/projects/jayek.webp",
    "assets/projects/electronic_contracts.webp",
    "assets/projects/h2h.webp",
    "assets/projects/stories.webp",
    "assets/projects/almotaheda.png",
    "assets/projects/helpers.webp",
  ];

  static const List<String> titles = [
    "Hayat Almuslim",
    "Bank El-Dam App",
    "Tejara E-Commerece",
    "Wardi E-Commerece",
    "Afaky ERP",
    "Gala Order",
    "Gala Driver",
    "QR Generator & Scanner",
    "أكاديمية علمني",
    "Jayek",
    "العقود الإلكترونية",
    "H2H",
    "ستوريات 2022",
    "ALMOTAHDA GROUP",
    "Helpers",
  ];

  static const List<String> description = [
    "For All Muslims This App Contains Quran, Hadith, Tafseer, Learning Quran, Azkar, Sebha And More Uploaded On Google Play",
    "This App For Collect Blood From All Users To Hospitals And Others Need This Blood Uploaded On Google Play And App Store",
    "This App For E-Commerce Uploaded On Google Play And App Store",
    "This App For E-Commerce Uploaded On Google Play And App Store",
    "This App Is ERP System Mobile Version App And Also Work On Web , It Uploaded On Google Play And App Store",
    "This App For Food Ordering That You Can Order Food From Any Restaruant And Delivery Will Deliver It To You And It Has Delivery App And Two Control Panels For Admin And Restaurant And It Uploaded On Google Play And App Store",
    "This App For The Delivery Of Gala Order App",
    "This App For Generate And Scan QR Code And Extrac All Data You Generated It Uploaded On Google Play",
    "This App Is Webview Based App For Allemny Academy Uploaded On Google Play",
    "This App For Ordering Your Food But It Special You Will Go And Get Your Food No One Will Deliver It For You And It Has Restaurant Panel And Admin Panel And It Uploaded On Google Play",
    "This App For Manage All Your Contracts And Buildings From Your Phone",
    "This App For Buy And Sell All Your Products And Goods Or Change It With Other People As You Need In Less Time",
    "Download All Whatsapp Stories From One App",
    "Website For Almotaheda Group To Show There All Projects",
    "For Asking And Answers Videos And Normal Questions",
  ];

  static const List<String> links = [
    "https://play.google.com/store/apps/details?id=com.quran_and_azkar.quran_and_azkar_app",
    "https://apps.apple.com/eg/app/%D8%A8%D9%86%D9%83-%D8%A7%D9%84%D8%AF%D9%85/id1547670843?l=ar",
    "https://apps.apple.com/us/app/tejara/id1540453728",
    "https://apps.apple.com/eg/app/%D9%85%D8%AA%D8%AC%D8%B1-%D9%88%D8%B1%D8%AF%D9%8A-wardi-store/id1560876131?l=ar",
    "https://apps.apple.com/us/app/afaky-app/id1622146478",
    "https://apps.apple.com/us/app/gala-order/id1640057386",
    "https://play.google.com/store/apps/details?id=com.gala.gala_rider",
    "https://play.google.com/store/apps/details?id=com.mohamednagdy.qrscannerandreader",
    "https://play.google.com/store/apps/details?id=com.u3allemny.allemny",
    "https://play.google.com/store/apps/details?id=com.jayekapp.jayek",
    "https://play.google.com/store/apps/details?id=com.ejar.electronic_contracts",
    "https://play.google.com/store/apps/details?id=com.rainmaker.goods_change",
    "https://play.google.com/store/apps/details?id=com.storiesstore.store",
    "https://almotahdagroup.com/",
    "https://apps.apple.com/us/app/helpers/id6444851510",
  ];
}
